# Generated by Django 4.2 on 2023-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0002_animal_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
